### ISSUE TITLE
Test Failure

### ISSUE THREAD

**Issue by Prapi123** [signetlabdei/sem#31]
Hello, 

I am trying to install SEM and facing below errors while running tests.

![image](https://user-images.githubusercontent.com/54693802/69040195-6bf38800-0a13-11ea-8ade-2606d0421eb5.png)

![image](https://user-images.githubusercontent.com/54693802/69040321-a1987100-0a13-11ea-9876-f7dcdb69ea3d.png)

Please guide me in correcting these errors.
Thanks in Advance

**Comment by DvdMgr** [comment]
Hi!
Running tests should not be necessary, as it is needed only if you want to
modify the library - if you just want to use it, it's enough to run pip3
install sem!

**Comment by Prapi123** [comment]
Hello
You can close this issue.


Thanks
