### ISSUE TITLE
Exception: ns-3 repository is not clean

### ISSUE THREAD

**Issue by matbord** [signetlabdei/sem#43]
Hi,
I just started to study this library.
I cloned the develop branch and I'm trying to run the WiFi plots example. When I run the following code 
`ns_path = '../../ns3'
script = 'wifi-multi-tos'
campaign_dir = "results"
campaign = sem.CampaignManager.new(ns_path, script, campaign_dir, overwrite=True)`
I obtain the following exception: Exception: ns-3 repository is not clean.
What does it mean?

**Comment by matbord** [comment]
Solved, I had only to commit all the changes of my NS3 repo

**Comment by DvdMgr** [comment]
This is the preferred solution for when you have to share the code, as it enforces only working on well defined revisions of the code. Alternatively, and especially if you are using SEM to do ns-3 code development, you can also set the [`check_repo`](https://simulationexecutionmanager.readthedocs.io/en/develop/api.html#sem.CampaignManager.new) argument to `False` when you create the campaign object!
