### ISSUE TITLE
Compilation ended with an error

### ISSUE THREAD

**Issue by matbord** [signetlabdei/sem#44]
Hi, 
I'm trying to run the WIFI plots.ipynb file and I cannot understand why I get this error. Can someone help me please ?
Here below there is the screenshot of the error

![Screenshot_2021-06-03 WiFi Plots - Jupyter Notebook](https://user-images.githubusercontent.com/45484331/120641427-de03b480-c473-11eb-9f1c-023db69750a4.png)

**Comment by DvdMgr** [comment]
Looks like something went wrong during compilation of ns-3. Do you get any errors if you just call `./waf` in the ns-3 repository?

**Comment by matbord** [comment]
@DvdMgr I get no errors, 'build' finished successfully. I tried to reinstall SEM and NS-3 but I have the same error, so nothing changed

**Comment by DvdMgr** [comment]
Ok, can you share the version of ns-3 and sem you are using? How did you
install sem?

**Comment by matbord** [comment]
I'm actually using a virtual machine on Windows: I cloned the repo from the branch "develop" and I'm currently using NS-3 available in the following repository https://github.com/nyuwireless-unipd/ns3-mmwave .  To install it I run the following line:  
`pip install -U pipenv`
then cloned the two repos and I executed the following commands inside the SEM folder:
`pipenv install --dev`
`pip3 install --user sem`

In the NS-3 folder I builded NS-3 with:
`./build.py --enable-examples --enable-tests`
`./waf`
If I run a script directly from the terminal using NS-3 it's working without any error but if I run the SEM's example I get the error. 

I used the same repositories (and I'm pretty sure the same commands) in an another PC with Linux installed from scratch (no virtual machine): it's working correctly but I'm actually trying to install it in a more powerful machine.

**Comment by DvdMgr** [comment]
Note that the development installation change on the develop branch, as we now use poetry to manage the environment. Can you try with the updated instructions? If you select develop as the branch on the main github repository page, they should appear down below in the readme.

Alternatively, if you are not interested in modifying your local SEM installation, you can also use the following command to install it directly:
`pip3 install --user https://github.com/signetlabdei/sem/archive/develop.zip`
