### ISSUE TITLE
module 'sem.utils' has no attribute 

### ISSUE THREAD

**Issue by matbord** [signetlabdei/sem#49]
Hi, 
I downloaded SEM develop branches in 2 computers.
The first one is my personal one and is working perfectly while the second one (UNIPD DEI lab) gives me the following error **module 'sem.utils' has no attribute ...** for each of the attribute I assign to sem.utils (Eg module 'sem.utils' has no attribute 'yelds_multiple_results' or output_lables(['a','b']) )

Do you know how to solve it?

**Comment by DvdMgr** [comment]
Is it possible you are not actually using the develop version of SEM on the second computer? The decorators are not available outside of develop, so the fact that you can import sem but not use them might mean you are using an old version. 

Unfortunately, python packaging can get messy. Have you tried completely purging sem from your pc, before installing it? Look for possible installations in `.local`, and try issuing `pip3 uninstall --user sem` both with sudo and without, and both with and without the `--user` option!

**Comment by matbord** [comment]
ok, uninstalling it and then installing SEM again with **pip3 install --user -U https://github.com/signetlabdei/sem/archive/develop.zip** works, thankyou!
