### ISSUE TITLE
Using DRMAA clusters for parallel execution of simulations

### ISSUE THREAD

**Issue by matbord** [signetlabdei/sem#50]
I would like to use the DRMAA: from the documentation I saw I have to use the method `create_runner(script,runner_type=’Auto’,optimized=True,skip_configuration=False,max_parallel_processes=None)` and set runner_type=GridRunner.
I don't understand where do I have to create this runner? and once I create it, how can I run all the simulations?

To make it easy, if I have the following basic code, what do I have to change to use the DRMAA?
```
campaign  = sem.CampaignManager.new(ns_path, script, campaign_dir, overwrite=False, check_repo=False)
paramstot = contains the parameters for my simulation                                         
campaign.run_missing_simulations(paramstot, runs=4)
resultDF  = campaign.get_result_as_dataframe(methodname, labels)
```

**Comment by DvdMgr** [comment]
DRMAA support is experimental and wasn't tested very thoroughly. Furthermore, this might also not be the best solution if you are executing SEM from a "login" node that should only be used for submission, as the main process will still consume resources on the login node and possibly raise some sysadmin eyebrows.

I'm working on better support for SLURM, and thinking about dropping DRMAA support - in the meantime, if you want to run SEM on a cluster, you can use the parallel runner as normal, and simply submit your python script to the cluster as a single job. If, for instance, you request 32 CPUs to the cluster, make sure to set `max_parallel_processes` to 32 and launch your script on the cluster using `qsub`/`sbatch`. The process will use all the available CPUs, and the efficiency of resource utilization will be almost the same as with the gridrunner.

**Comment by matbord** [comment]
ok, I'll try, thankyou very much!

**Comment by matbord** [comment]
I have a question to use the cluster. As you said, if I request 32 CPUs to the cluster, I have to set max_parallel_processes=32. 

```
ns_path` = '../ns3'
script = 'script_name'
campaign_dir = "../results"
campaign = sem.CampaignManager.new(ns_path, script, campaign_dir, overwrite=False, check_repo=False, max_parallel_processes=32)
```
if I set in the SLURM file #SBATCH --ntasks 32, I get the following error *32 times
```
Traceback (most recent call last):
  File "run_simulation.py", line 32, in <module>
    campaign = sem.CampaignManager.new(ns_path, script, campaign_dir, overwrite=False, check_repo=False, max_parallel_processes=32)
  File "/home/bordinmatt/.local/lib/python3.6/site-packages/sem/manager.py", line 124, in new
    max_parallel_processes=max_parallel_processes)
  File "/home/bordinmatt/.local/lib/python3.6/site-packages/sem/manager.py", line 200, in load
    max_parallel_processes=max_parallel_processes)
  File "/home/bordinmatt/.local/lib/python3.6/site-packages/sem/manager.py", line 239, in create_runner
    max_parallel_processes=max_parallel_processes)
  File "/home/bordinmatt/.local/lib/python3.6/site-packages/sem/runner.py", line 60, in __init__
    skip_configuration=skip_configuration)
  File "/home/bordinmatt/.local/lib/python3.6/site-packages/sem/runner.py", line 158, in configure_and_build
    for current, total in line_iterator:
  File "/home/bordinmatt/.local/lib/python3.6/site-packages/sem/runner.py", line 183, in get_build_output
    process.stdout.read()))
Exception: Compilation ended with an error.
STDERR
b"Build failed\n-> missing file: '/nfsd/signet3/bordinm/ns3-thesis/build/optimized/src/core/examples/ns3-dev-sample-random-variable-stream-optimized'\n"
STDOUT
b''
```
Am I doing something wrong?
