### ISSUE TITLE
ModuleNotFoundError: No module named 'sem' DEI Account

### ISSUE THREAD

**Issue by matbord** [signetlabdei/sem#52]
Hi,
I'm using my DEI account from home and I'm connecting using SSH. I installed SEM with

`pip3 install --user -U https://github.com/signetlabdei/sem/archive/develop.zip`
and then I cloned the "develop" branch.
When I run my SCRUM file I get this error

```Traceback (most recent call last):
  File "sem_file.py", line 2, in <module>
    import sem
ModuleNotFoundError: No module named 'sem'
Traceback (most recent call last):
  File "thesis_scrum1.py", line 2, in <module>
    import sem
ModuleNotFoundError: No module named 'sem'
```

I already tried to do 'pip3 uninstall sem' and reinstalling it but the error persists. 
Does someone have some experience with it?

**Comment by DvdMgr** [comment]
Cloning the develop branch should not be necessary when installing the .zip archive through `pip`. How are you running the script? Make sure to run as the user you installed `sem` as, and call the script with the `python3` command (annoyingly, Python 2 is still linked to the `python` command on some distributions).

**Comment by matbord** [comment]
If I run the script locally it's working but if I run it using the cluster using the SCRUM file I get the error mentioned before.
The scrum file is the following 
```
#!/bin/bash

#SBATCH --job-name SEM_NS3
#SBATCH --output output_%j.txt
#SBATCH --error errors_%j.txt
#SBATCH --ntasks 32
#SBATCH --partition allgroups
#SBATCH --mem 16G

cd ../sem/examples
srun python3 SEM_NS3_scrypt.py

```
and I'm executing it from my DEI account where SEM is installed

**Comment by DvdMgr** [comment]
Can you try installing from within the cluster, by adding the `pip3 install` line before `cd ../sem/examples` in your job submission file?

**Comment by matbord** [comment]
ok , it's working, thankyou!
