### ISSUE TITLE
Delete specific simualtion from result folder

### ISSUE THREAD

**Issue by matbord** [signetlabdei/sem#55]
Hi,
I would like to delete specific simulations from my results. What is the best way to do it? In the documentation, I saw that there is the method `delete_result(result)`  . If it's correct can I see an example code on how to apply it?

**Comment by DvdMgr** [comment]
Yes, you can use `delete_result`, directly passing to it the result you want to delete! A quick example, in which we delete results that have `RngRun` value set to 3 from the database:
```python
for result in campaign.db.get_complete_results():
    if result['params']['RngRun'] == 3:
        campaign.db.delete_result(result)
```

Of course, make sure to backup your results folder before experimenting with this.
