### ISSUE TITLE
No module named 'poetry.masonry'

### ISSUE THREAD

**Issue by MarshallAsch** [signetlabdei/sem#56]
I believe that this line:

 https://github.com/signetlabdei/sem/blob/e900dd136c9f9a3f2994f071907eead39cc96e13/pyproject.toml#L46 

should be 
`build-backend = "poetry.core.masonry.api"`
It is causing issues  when I have `sem = {git = "https://github.com/signetlabdei/sem", rev = "develop"}` in my pyproject.toml file

This is also preventing the develop branch from being loaded using pip install from a requirements file

**Comment by DvdMgr** [comment]
Fixed in #57 - thanks!
