### ISSUE TITLE
Error: "No such file or directory: 'path-to-ns3/build/build-status.py'"

### ISSUE THREAD

**Issue by non-det-alle** [signetlabdei/sem#59]
Hello,

Trying to use the module with new freshly-built versions of ns-3 produces this error: "No such file or directory: 'path-to-ns3/build/build-status.py'". The new `./ns3` script writes the same info in `.lock-ns3_linux_build` in the main ns-3 dir ([for reference](https://gitlab.com/nsnam/ns-3-dev/-/blob/master/test.py#L1126)). I think the error is produced by the code in `runner.py`, but there may be other instances.

**Comment by pagmatt** [comment]
Hi, 

We are currently working on this. If you happen to be in a hurry (and to use Linux), you can try the branch `new-buildsystem-fix`. However, please be aware that it is an experimental development branch.
